spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 500
          multiplier: 2
          max-interval: 5000
          
    
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:testesdeapp.naoresponda@gmail.com}
    password: ${MAIL_PASSWORD:frcobfqazecsyxyp}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true} 
    

server:
  port: 8082
